### ISSUE TITLE
Only local connections are allowed.

### ISSUE THREAD

**Issue by TheFifthFreedom** [selenodium/selenodium-grid#41]
This is more of a question and less of an issue. Following https://github.com/selenodium/selenodium-grid/pull/40, I noticed in the log of the node which was running the test something I was intrigued by:

```
16:33:08.500 INFO - Executing: [new session: Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]])
16:33:08.506 INFO - Creating a new session for Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]
Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 42882
Only local connections are allowed.
16:33:09.488 INFO - Done: [new session: Capabilities [{browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]]
16:33:09.515 INFO - Executing: [get: http://www.google.com])
16:33:10.748 INFO - Done: [get: http://www.google.com]
16:33:40.764 INFO - Executing: [get page source])
16:33:40.782 INFO - Done: [get page source]
16:33:40.812 INFO - Executing: [delete session: c2ef2b36-d3b9-42e6-971f-13dfb0319d08])
16:33:41.378 INFO - Done: [delete session: c2ef2b36-d3b9-42e6-971f-13dfb0319d08]
```

I'm referring to `Only local connections are allowed.`. Now this only appears when using ChromeDriver, and not any other driver. Google led me there:
http://stackoverflow.com/questions/25080500/when-run-webdriver-with-chrome-browser-getting-message-only-local-connection
which seems to suggest that on a grid setup, this message shouldn't appear. I tried running my test with the server on one computer and the node on another (but on the same network), and even using Selenium's official Java server, but I got this message still popping up. It's all working fine though, and not related to `selenodium` directly, but I wanted to ask your opinion on this @arikon . I might try it again with a VM on a different network as a node to see what happens.

**Comment by arikon** [comment]
@TheFifthFreedom Here are two quotes from the link you provided =)

> This is an informational message only. What the message is telling you is that the chromedriver executable will only accept connections from the local machine.
> 
> This is an informational message only. It means nothing if your test scripts and chromedriver are on the same machine then it is possible to add the "whitelisted-ips" option. your test will run fine.

What about grid setup:

> However if you use chromedriver in a grid setup, this message will not appear

If you run `chromedriver` by hand and make it to connect to the grid then it will not output such a message. But I'm not sure if it is possible. In our case `chromedriver` is launched by `selenium-server -role node` process.

**Comment by TheFifthFreedom** [comment]
Thanks for clarifying this for me @arikon !
