### ISSUE TITLE
/grid/console/ vs /wd/hub/status

### ISSUE THREAD

**Issue by TheFifthFreedom** [selenodium/selenodium-grid#42]
I noticed in `server.js`'s servlet routes a few entries I didn't recognize from the Selenium Grid v2 Protocol (https://github.com/nicegraham/selenium-grid2-api):

``` javascript
'/wd/hub/status': notImplementedServlet,
'/wd/hub/sessions': notImplementedServlet,
'/wd/hub/session': requestServlet
```

and I didn't see `/grid/console/` or `/grid/beta/console/` either. Is `/wd/hub/status` meant to replace `grid/console`?

**Comment by arikon** [comment]
> Is `/wd/hub/status` meant to replace `grid/console`?

@TheFifthFreedom No. It is for program-readable status of the hub. See examples here: https://github.com/nicegraham/selenium-grid2-api#wdhub

`/grid/console` is not implemented at all (and for now it not planned). I think it could be implemented as a separate plugin when we'll have plugin API.

**Comment by TheFifthFreedom** [comment]
OK that makes sense! There are some existing plugins for the official Selenium Grid implementation which rely on the /grid/console route to retrieve available nodes programmatically (https://github.com/davglass/selenium-grid-status), but it would make more sense as you say to simply have one plugin that takes care of that without relying on a servlet route that is of little use otherwise.
